version: "3.9"
services:
    node-app:
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=5000
            - MONGO_USER=adra
            - MONGO_PASSWORD=1234
        depends_on:
            - mongo
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=adra
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - mongo-db:/data/db
    redis:
        image: redis

volumes:
    mongo-db:
